### ISSUE TITLE
Option to revert study window back to real time?

### ISSUE THREAD

**Issue by Er-o-ck** [Cediner/ArdClient#59]
### Discussed in https://github.com/Cediner/ArdClient/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **Er-o-ck** September 13, 2022</sup>
Does this option exist I can't find it anywhere if it does. Not liking that my curios are displaying in-game time. Very confusing and has no real practical use for me.</div>

**Comment by AwonGardino** [comment]
There is a checkbox in "Item overlay", that says "Show study time" "Real time", but it only shows real time in a corner of curio icon.

Tbh i dont realy get it, why somebody need to know ingame time? Its the most useless information, since nobody realy cares about ingame time at all. Even seasons are measured in real days. We realy need an option to hide all ingame time displayment and leave real life time only.

**Comment by Cediner** [comment]
Discord users are jorb#8519 and Loftar#9957 will answer your questions

**Comment by AwonGardino** [comment]
No, they will not.
Other clients dont have same issue, so its clientside, not serverside.
